#!/bin/sh
# cbuildtar rev. 24 July 2013 by Stuart Ambler.
# Copyright (c) 2013 Stuart Ambler.
# Distributed under the Boost License in the accompanying file LICENSE.

tar czvf stuartcsample.tar.gz c/Makefile c/README.md c/timing.txt c/pqueue.h c/pqueue.c c/mmerge.h c/mmerge.c c/testmmerge.h c/testmmerge.c c/testmmergemain.c c/checktestmmerge.c c/buildmmerge c/testmmergemain c/checktestmmerge common/* c/testdata.txt c/Rout.txt c/*.pdf c/runvalgrind c/vgsupp c/valgrindout.txt cbuildtar LICENSE
