#!/bin/sh
# ccbuildtar rev. 24 July 2013 by Stuart Ambler.
# Copyright (c) 2013 Stuart Ambler.
# Distributed under the Boost License in the accompanying file LICENSE.

tar czvf stuartccsample.tar.gz cc/Makefile cc/README.md cc/timing.txt cc/mmerge.h cc/mmerge.cc cc/testmmerge.h cc/testmmerge.cc cc/testmmergemain.cc cc/cppunittestmmerge.cc cc/buildmmerge cc/testmmergemain cc/cppunittestmmerge common/* cc/testdata.txt cc/Rout.txt cc/*.pdf cc/runvalgrind cc/vgsupp cc/valgrindout.txt ccbuildtar LICENSE
