#!/bin/sh
# commonbuildtar rev. 23 July 2013 by Stuart Ambler.
# Copyright (c) 2013 Stuart Ambler.
# Distributed under the Boost License in the accompanying file LICENSE.

tar czvf stuartcommonsample.tar.gz common/* LICENSE
