#!/bin/sh
# rubybuildtar rev. 24 July 2013 by Stuart Ambler.
# Copyright (c) 2013 Stuart Ambler.
# Distributed under the Boost License in the accompanying file LICENSE.

tar czvf stuartrubysample.tar.gz ruby/Makefile ruby/README.md ruby/timing.txt ruby/mmerge.rb ruby/testmmerge.rb common/* ruby/testdata.txt ruby/Rout.txt ruby/*.pdf ruby/doc/* ruby/runrspec ruby/spec/* rubybuildtar LICENSE
