#!/bin/sh
# cc/buildmmerge rev. 23 July 2013 by Stuart Ambler.
# Copyright (c) 2013 Stuart Ambler.
# Distributed under the Boost License in the accompanying file LICENSE.

g++ -std=c++11 testmmergemain.cc testmmerge.cc mmerge.cc -largtable2 -o testmmergemain
g++ -std=c++11 cppunittestmmerge.cc testmmerge.cc mmerge.cc -largtable2 -lcppunit -o cppunittestmmerge
