#!/bin/sh
# java/buildmmerge rev. 23 July 2013 by Stuart Ambler.
# Copyright (c) 2013 Stuart Ambler.
# Distributed under the Boost License in the accompanying file LICENSE.

javac -Xlint:all -cp .:/usr/share/java/junit4.jar:/usr/share/java/jopt-simple-4.5.jar com/zulazon/samples/MMerge.java com/zulazon/samples/GetCfgOutput.java com/zulazon/samples/GenerateDataOutput.java com/zulazon/samples/TestMMerge.java com/zulazon/samples/JUnitTestMMerge.java
